#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import os,sys,re,ast,random,time,datetime,pyttsx3,traceback
try:
	import thread
	import urllib
except:
	import _thread as thread
	import urllib.request as urllib

# Find iandi's resources folder and set it as working dir
wdir=""
paths=[
	"./",
	os.path.expanduser("~")+"/.iandi/",
	os.popen("xdg-user-dir DOCUMENTS").read().replace("\n","")+"/iandi/",
	os.popen("xdg-user-dir DOWNLOAD").read().replace("\n","")+"/iandi/",
	"/var/lib/iandi/",
	"/etc/iandi/",
	"/usr/local/etc/iandi/",
	"/usr/local/share/iandi/",
	"/usr/share/iandi/",
]
for path in paths:
	if os.path.exists(path):
		if os.path.exists(path+"/brains"):
			wdir=path
			break
if wdir!="":
	os.chdir(wdir)
	sys.path.insert(0,wdir)
else:
	print("Iandi's resources folder not found.")
	quit(2)

import iso639,snowboydecoder
import globalvars
try:
	import terminal_virtualface as virtualface
	globalvars.virtualface_enabled=True
except:
	globalvars.virtualface_enabled=False
from pocketsphinx import LiveSpeech
import speech_recognition as sr
from playsound import playsound
from rmem import *
from difflib import SequenceMatcher
if os.name!="nt":
	try:
		import procname
		procname.setprocname("Iandi")
	except:
		pass

globalvars.version="0.1.1"

# Functions
#from internals import *

if sys.version_info[0]>2:
	def raw_input(txt):
		return(input(txt))

def log(txt):
	# Append a line to log with timestamp
	txt=str(datetime.datetime.now().strftime("%Y.%m.%d.%H.%M.%S"))+" - "+str(txt)
	print(txt)
	with open("/tmp/iandi.log","a") as log:
		log.write(txt+"\n")
		log.close()

def quit(exitCode,speak=True):
	try:
		if speak:
			if "CBM" in globalvars.brain:
				globalvars.cm=resultcode(globalvars.brain["CBM"])
				output(globalvars.cm)
			else:
				output("Exit...")
		
		if globalvars.executiontype!="lite":
			globalvars.detector.terminate()

		globalvars.faceExecuting=False
		os.system("tput cnorm")
	except Exception as e:
		log(traceback.format_exc())
	
	exit(exitCode)

def addhistory(txt):
	# Add last used command to history, with a max of 10 commands
	globalvars.history.append(txt)
	if len(globalvars.history)>10:
		globalvars.history.pop(0)
def readurl(url):
	# Retrun page content of url
	page=urllib.urlopen(url)
	content=page.read()
	page.close()
	return content
def encode(o):
	try:
		o=str(o)
	except:
		pass
	if sys.version_info[0]<3:
		try:
			o=unicode(o,"utf-8")
		except:
			pass
	return o
def encode2(o):
	try:
		o=str(o)
	except:
		pass
	if sys.version_info[0]<3:
		try:
			o=unicode(o,"utf-8")
		except:
			pass
		try:
			o=o.encode('utf8')
		except:
			pass
	return o
def similar(a,b):
	# Return percentage of similarity between A and B
	try:
		a=encode(a)
	except:
		pass
	try:
		b=encode(b)
	except:
		pass
	return SequenceMatcher(None,a,b).ratio()
def getlang():
	# Return current language setted
	return mem["lang"]
def setbrain():
	try:
		brainfile="brains/"+getlang()+".brain"
		if not os.path.isfile(brainfile):
			log("Lang "+iso639.get_eng(getlang())+" not supported in brains. Swithing to english.")
			updlang("eng")
			brainfile="brains/eng.brain"
		tbrain=open(brainfile,"r")
		globalvars.brain=ast.literal_eval(tbrain.read())
		tbrain.close()
	except Exception as e:
		log(brainfile+" error: "+str(traceback.format_exc()))
		globalvars.brain={}
	globalvars.brainlang=mem["lang"]
def checklang():
	if globalvars.brainlang!=mem["lang"]:
		setbrain()
def updlang(newlang,returnString=False):
	setlang(newlang)
	setbrain()
	if returnString:
		return "English setted as language."
def sttmodel(lang=""):
	# Return speech to text model's files
	availablelangs=list(os.walk("sttlangs/"))[0][1]
	if not lang in availablelangs:
		for al in availablelangs:
			if lang.lower()==al.lower().split("-")[0]:
				lang=al
			if not lang in availablelangs:
				lang="eng"
	modelpath="sttlangs/"+lang+"/"
	modelfiles=list(os.walk(modelpath))[0]
	hmm=modelpath+modelfiles[1][0]+"/"
	for f in modelfiles[2]:
		if f.endswith(".lm.bin"):
			lm=modelpath+f
		if f.endswith(".dict"):
			dic=modelpath+f
	return [hmm,lm,dic]
def voice(txt):
	if txt!=None and txt!="":
		maxwordsforonline=60
		onlinetts=False
		if globalvars.onlineconnection and len(txt.split(" "))<=maxwordsforonline and onlinetts:
			# Demo version of IBM tts with italian voice. Test purpose only, so keep "onlinetts" var to false.
			urllib.urlretrieve('https://text-to-speech-demo.ng.bluemix.net/api/v3/synthesize?text='+urllib.quote(encode2(txt))+'&voice=it-IT_FrancescaVoice&download=true&accept=audio%2Fmp3',"/tmp/voice.mp3")
		else:
			if globalvars.rvoicelang!=getlang():
				globalvars.rvoicelang=getlang()
				globalvars.voicelang=iso639.get_iso1(globalvars.rvoicelang)
				if not globalvars.voicelang:
					globalvars.voicelang=globalvars.rvoicelang
				globalvars.voicelang=globalvars.voicelang.lower()
				globalvars.voicetts.setProperty("voice",globalvars.voicelang+"+f1")
			globalvars.voicetts.say(txt)
		globalvars.voicebusy=True
		if globalvars.onlineconnection and len(txt.split(" "))<=maxwordsforonline and onlinetts:
			playsound("/tmp/voice.mp3")
		else:
			globalvars.voicetts.runAndWait()
		#
		globalvars.voicetts.stop()
		globalvars.voicebusy=False
def face():
	globalvars.faceExecuting=True

	oldc=globalvars.c
	if globalvars.virtualface_enabled:
		os.system("tput civis")
	while globalvars.faceExecuting:
		if globalvars.c!="":
			oldc=globalvars.c
		if globalvars.virtualface_enabled:
			if globalvars.voicebusy:
				virtualface.face(speak=True,expr=globalvars.expr)
			else:
				virtualface.face()
		else:
			os.system('cls' if os.name=='nt' else 'clear')
		print(oldc)
		if globalvars.virtualface_enabled:
			time.sleep(.1)
		else:
			time.sleep(1)
	os.system("tput cnorm")
def resultcode(cm,args=[]):
	if cm!=None:
		if "|&|" in cm:
			cm=cm.split("|&|")[(random.randrange(0,len(cm.split("|&|"))))]
	if cm!=None:
		if cm.startswith(":goto:") and cm.endswith(":goto:"):
			if cm[6:-6] in globalvars.brain:
				cm=resultcode(globalvars.brain[cm[6:-6]],args)
	if cm!=None:
		if cm.startswith("exec%=%") and cm.endswith("%=%exec"):
			try:
				if sys.version_info[0]>2:
					_locals=locals()
					exec("cm="+"".join(re.findall('exec%=%(.*?)%=%exec',cm)),globals(),_locals)
					cm=_locals["cm"]
				else:
					exec("cm="+"".join(re.findall('exec%=%(.*?)%=%exec',cm)))
			except KeyboardInterrupt:
				quit(0)
			except Exception as e:
				log(getattr(e,"message",e))

				if "ERR" in globalvars.brain:
					cm=globalvars.brain["ERR"] # ERR must be only string to avoid problems and recursion over them
				else:
					cm="Error, check the log."
	if cm==None:
		cm=""
	return cm
def elabout(s,outfn):
	f=[] # [type,in]
	outhist=[]

	def printInLine(txt):
		sys.stdout.write(encode2(txt))
		sys.stdout.flush()

	if outfn=="print":
		outfn=printInLine

	search=re.findall(r'<<exec<(.*?)>exec>>',s)
	if len(search)>0:
		for i,r in enumerate(search):
			estr="<<exec<{}>exec>>".format(r)
			pre=s.split(estr)[0]
			if pre!="":
				f.append(["str",pre])
			f.append(["exe",r])
			s=estr.join(s.split(estr)[1:])
			if i==len(search)-1 and len(s)>0:
				f.append(["str",s])
	else:
		f.append(["str",s])

	for i,e in enumerate(f):
		if e[0]=="str":
			outhist.append(e[1])
			if outfn==printInLine:
				outfn("".join(outhist)+"\r")
			else:
				outfn(e[1])
		elif e[0]=="exe":
			exec("exertn="+e[1],globals())
			if exertn!=None:
				outhist.append(str(exertn))
				if outfn==printInLine:
					outfn("".join(outhist)+"\r")
				else:
					outfn(str(exertn))
		if i==len(f)-1 and outfn==printInLine:
			printInLine("\n")
def output(o,close=True,setexpr=[]):
	newinput=False
	o=encode(o)
	if o.startswith("<<callbrain<") and o.endswith(">callbrain>>"):
		callBrain(o[12:-12])
	else:
		if o.startswith("<<newinput<") and o.endswith(">newinput>>"):
			newinput=True
			o,f=o[11:-11].split("<,>")
			farg=""
			if "," in f:
				farg=",".join(f.split(",")[1:])+","
				#farg=f.split(",")[1:]
				#for i,arg in enumerate(farg):
				#	if not "(" in arg and not "[" in arg and not "{" in arg:
				#		farg[i]=repr(arg)
				#farg=",".join(farg)+","
				f=f.split(",")[0]
		if globalvars.executiontype=="lite":
			#print(o)
			elabout(o,"print")
		else:
			exprl=[]
			for e in setexpr:
				globalvars.expr.append(e)
				exprl.append(len(globalvars.expr)-1)
			if o!="":
				try:
					#voice(o) #thread.start_new_thread(voice,(o,))
					elabout(o,voice)
				except KeyboardInterrupt:
					quit(0,False)
				except Exception as err:
					log(traceback.format_exc())
					quit(1)
			for e in exprl:
				globalvars.expr.pop(e)
		if newinput:
			exec("output("+f+"("+farg+str(sinput().split(" "))+"))")
		else:
			if close:
				globalvars.notcheckword=False
				if globalvars.executiontype!="lite":
					playsound("resources/sounds/peeb.ogg")

def callBrain(c):
	globalvars.c=c
	if globalvars.c!=globalvars.exitcommand:
		rawc=globalvars.c
		globalvars.c=globalvars.c.lower()
		if globalvars.c in globalvars.brain:
			addhistory(globalvars.c)
			globalvars.cm=resultcode(globalvars.brain[globalvars.c])
			output(globalvars.cm)
		else:
			atto=0
			attn=""
			num=0
			cwords=globalvars.c.split(" ")
			rawcwords=rawc.split(" ")
			for a in globalvars.brain:
				for n,word in enumerate(cwords):
					ccutted=" ".join(cwords[:len(cwords)-n])
					if similar(ccutted,a)>=globalvars.anstollerance:
						if similar(ccutted,a)>atto:
							atto=float(similar(ccutted,a))
							attn=a
							args=rawcwords[len(rawcwords)-n:]
			if atto!=0:
				globalvars.c=attn
				#print("> {}".format(globalvars.c))
				#print("< Args: {}".format(args))
				addhistory(globalvars.c)
				globalvars.cm=resultcode(globalvars.brain[globalvars.c],args)
				output(globalvars.cm)
			elif "CNFE" in globalvars.brain:
				addhistory("CNFE")
				globalvars.cm=resultcode(globalvars.brain["CNFE"])
				if globalvars.history[-3:]!=["CNFE","CNFE","CNFE"]:
					closeAft=False
				else:
					closeAft=True
				output(globalvars.cm,close=closeAft,setexpr=["eyes-semi-closed"])
			else:
				addhistory("CNFE")
				if globalvars.history[-3:]!=["CNFE","CNFE","CNFE"]:
					closeAft=False
				else:
					closeAft=True
				output("Command not found.",close=closeAft)
	else:
		quit(0)

def sr_adjust():
	while True:
		if globalvars.onlineconnection:
			with sr.Microphone() as source:
				globalvars.r.adjust_for_ambient_noise(source)
		time.sleep(10800)
def googleSTT(first=True,lang=""):
	with sr.Microphone() as source:
		if first:
			rlang=getlang()
			lang=iso639.get_iso1(rlang)
			if not lang:
				lang=rlang
			playsound("resources/sounds/beep.ogg")
			first=False
		audio=globalvars.r.listen(source)
		try:
			o=globalvars.r.recognize_google(audio,language=lang)
		except Exception as e:
			log("googleSTT error: {}".format(traceback.format_exc()))
			o=""
		if o=="":
			o=googleSTT(first,lang)
	return o
def deepspeech():
	lang=getlang()
	if not lang:
		lang=rlang
	if globalvars.executiontype=="noui":
		verbose="verbose"
	else:
		verbose=""
	#playsound("resources/sounds/beep.ogg") moved directly in deepspeechSTT.py
	out=os.popen("python3 deepspeechSTT.py {} {}".format(repr(lang),repr(verbose))).read()
	rout=out
	if verbose=="verbose":
		print(out)
	for i,line in enumerate(out.split("\n")):
		if line=="----":
			break
	out=" ".join(out.split("\n")[i+1:])
	out=out.replace("\n"," ").strip()
	if out=="":
		log("deepspeechSTT.py error: Segmentation fault")
		#out=deepspeech(lang)
	else:
		out=out[0].capitalize()+out[1:]
	return out
def sinput():
	if globalvars.executiontype=="lite":
		try:
			o=raw_input("> ")
		except KeyboardInterrupt:
			quit(0)
		except Exception as e:
			log(traceback.format_exc())
			quit(1)
	else:
		#playsound("resources/sounds/beep.ogg")
		pausemusic(False)
		if not globalvars.onlineconnection:
			# Pocketsphinx speech to text (offline)
			hmm,lm,dic=sttmodel(getlang())
			playsound("resources/sounds/beep.ogg")
			try:
				for o in LiveSpeech(hmm=hmm,lm=lm,dic=dic):
					if o!="":
						break
			except KeyboardInterrupt:
				quit(0)
			except Exception as e:
				log(traceback.format_exc())
				quit(1)
			
			# Mozilla speech to text (offline)
			#o=deepspeech()
		else:
			try:
				# Google speech to text (online)
				o=googleSTT()
			except KeyboardInterrupt:
				quit(0)
			except Exception as e:
				log(traceback.format_exc())
				quit(1)
	return encode(o)
def hotword():
	globalvars.notcheckword=True
def checkhotword():
	return globalvars.notcheckword
def checkOnlineConnection(onceCheck=False):
	host="https://lite.duckduckgo.com/lite/"#"1.1.1.1"
	checksleep=5.0
	neverConnected=True

	while True:
		try:
			readurl(host)
			globalvars.onlineconnection=True
			if neverConnected:
				globalvars.r=sr.Recognizer()
				thread.start_new_thread(sr_adjust,())
				neverConnected=False
		except Exception as e:
			globalvars.onlineconnection=False

		if onceCheck:
			break
		else:
			time.sleep(checksleep)

def iandiTrayIcon():
	import wx

	class trayIcon(wx.TaskBarIcon):
		def __init__(self,frame):
			self.frame=frame
			super(trayIcon,self).__init__()
			self.set_icon("resources/icons/icon-round2.png")
			#self.set_icon("resources/icons/icon-white.png")
		def set_icon(self,path):
			icon=wx.IconFromBitmap(wx.Bitmap(path))
			self.SetIcon(icon,"Iandi")

	class App(wx.App):
		def OnInit(self):
			frame=wx.Frame(None)
			self.SetTopWindow(frame)
			trayIcon(frame)
			return True
	
	app=App(False)
	app.MainLoop()

####

if __name__=="__main__":
	# Load brain
	setbrain()
	# Check execution type
	if len(sys.argv)>1:
		globalvars.executiontype=sys.argv[1].lower()
	else:
		globalvars.executiontype=""

	# Tray icon
	if globalvars.executiontype!="lite":
		if "DISPLAY" in os.environ:
			try:
				thread.start_new_thread(iandiTrayIcon,())
			except:
				pass

	# Check internet connection
	checkOnlineConnection(True)
	# Start internet connection checking thread
	thread.start_new_thread(checkOnlineConnection,())

	globalvars.voicetts=pyttsx3.init()
	globalvars.rvoicelang=getlang()
	globalvars.voicelang=iso639.get_iso1(globalvars.rvoicelang)
	if not globalvars.voicelang:
		globalvars.voicelang=globalvars.rvoicelang
	globalvars.voicelang=globalvars.voicelang.lower()
	globalvars.voicetts.setProperty("voice",globalvars.voicelang+"+f1")
	#globalvars.voicetts.setProperty("rate",150) # Slows down voice, default it's 200
	globalvars.voicebusy=False
	# Importing plugins
	if os.getcwd() in paths and os.path.exists(os.path.expanduser("~")+"/.iandi/"):
		os.chdir(os.path.expanduser("~")+"/.iandi/")
		sys.path.insert(0,os.path.expanduser("~")+"/.iandi/")

		from plugins import *

		os.chdir(wdir)
		sys.path.insert(0,wdir)
	else:
		from plugins import *
	#
	try:
		globalvars.anstollerance
	except:
		try:
			globalvars.anstollerance=anstollerance
		except NameError:
			globalvars.anstollerance=.65
	try:
		globalvars.exitcommand
	except:
		try:
			globalvars.exitcommand=exitcommand
		except NameError:
			globalvars.exitcommand="QUIT!"
	# history
	globalvars.history=[]
	###
	globalvars.c=""
	###
	# load face
	globalvars.expr=[]
	if globalvars.executiontype!="lite" and globalvars.executiontype!="noui":
		thread.start_new_thread(face,())
	###
	globalvars.notcheckword=False
	if globalvars.executiontype!="lite":
		model="resources/iandi.pmdl"#"alexa.umdl"#"computer.pmdl"
		snowboy_started=False
		while not snowboy_started:
			try:
				globalvars.detector=snowboydecoder.HotwordDetector(model,sensitivity=.4)
				snowboy_started=True
			except:
				pass
	if globalvars.executiontype=="lite":print("'"+globalvars.exitcommand+"' to exit\n---------------")
	if "SWM" in globalvars.brain:
		globalvars.cm=resultcode(globalvars.brain["SWM"])
		output(globalvars.cm)
	while globalvars.c!=globalvars.exitcommand:
		checklang()
		args=[]
		if globalvars.executiontype!="lite":
			try:
				if not musicgetifpaused():
					resumemusic(False)
			except:
				resumemusic(False)
			try:
				globalvars.detector.start(detected_callback=hotword,interrupt_check=checkhotword,sleep_time=0.03,verbose=False)
			except KeyboardInterrupt:
				quit(0)
			except Exception as e:
				log(traceback.format_exc())
				quit(1)
			#pausemusic(False)
		callBrain(sinput())
